# Produces the two build numbers the device reports, both as yymmdd-hhmmss.
#
# The firmware number is generated into include/build_number.h instead of being
# derived from __DATE__/__TIME__. Those macros record when one translation
# unit last recompiled, which on an incremental build is not when this image
# was produced.
#
# The frontend number is written into the data directory only while the
# filesystem image is packed, so it describes that image and nothing else. It
# travels inside the image and the firmware reads it back at startup.
Import("env")

import os
from datetime import datetime

STAMP_FORMAT = "%y%m%d-%H%M%S"


def stamp():
    return datetime.now().strftime(STAMP_FORMAT)


projectDirectory = env.subst("$PROJECT_DIR")
with open(os.path.join(projectDirectory, "include", "build_number.h"), "w") as header:
    header.write(
        "// Generated by tools/build_stamp.py on every build. Do not edit.\n"
        "#pragma once\n"
        "\n"
        "namespace build_number {\n"
        'constexpr char kFirmware[] = "' + stamp() + '";\n'
        "}  // namespace build_number\n"
    )


def writeFrontendStamp(source, target, env):
    dataDirectory = env.subst("$PROJECT_DATA_DIR")
    os.makedirs(dataDirectory, exist_ok=True)
    with open(os.path.join(dataDirectory, "build-stamp.txt"), "w") as stampFile:
        stampFile.write(stamp())


env.AddPreAction(
    os.path.join(env.subst("$BUILD_DIR"), env.subst("$ESP32_FS_IMAGE_NAME") + ".bin"),
    writeFrontendStamp,
)
